name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET Project
        run: dotnet publish TelegramMiniApp/TelegramMiniApp.csproj -c Release -o release --nologo

      - name: Copy index.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/"/<base href="\/TelegramMiniApp\/"/g' release/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: release/wwwroot